// src/views/Pulse/usePulseWire.ts
//
// The full-data hook behind The Pulse view. Merges two existing detectors
// into one ranked wire of plain-English WireItems:
//
//   1. Neighborhood VOLUME anomalies  (useAnomalyBaseline + the live 48h window)
//   2. Citywide signals               (useCivicIndicators — trends/tally/milestones)
//
// All prose is generated by the tested pure layer in @/lib/pulse/pulsePhrase.
// This hook only orchestrates: fetch, gate on freshness, rank.
//
// COST NOTE: this loads the full 48h event window (~6000 rows) because
// useAnomalyBaseline needs the current counts. That's the documented cost of
// the DEDICATED view — Home's teaser must NOT use this hook (it reads the
// already-cached indicators instead). See feedback_frontpage_load_perf.

import { useMemo } from 'react'
import { useCivicIndicators } from '@/hooks/useCivicIndicators'
import { useLast48Window } from '@/hooks/useLast48Window'
import { useAnomalyBaseline } from '@/hooks/useAnomalyBaseline'
import { LAST48_DATASETS } from '@/types/last48'
import {
  anomalyToWireItem,
  tickerToWireItem,
  rankWire,
  type WireItem,
} from '@/lib/pulse/pulsePhrase'

// A "quiet" reading is only trustworthy if the stream's freshest event is
// recent. If a stream hasn't published in over a day, a low 48h count is a
// publishing gap, not real quiet — suppress it (the Quakebot / "crashes -100%"
// trap). 24h comfortably clears all three live streams' normal cadence.
const FRESH_MAX_MS = 24 * 60 * 60 * 1000

export interface UsePulseWireResult {
  items: WireItem[]
  isLoading: boolean
}

export function usePulseWire(): UsePulseWireResult {
  const window48 = useLast48Window({ datasets: LAST48_DATASETS })
  const { anomalies } = useAnomalyBaseline({
    datasets: LAST48_DATASETS,
    currentEvents: window48.events,
  })
  const { items: tickerItems, isLoading: tickerLoading } = useCivicIndicators()

  const items = useMemo(() => {
    const now = Date.now()
    const wire: WireItem[] = []

    // Neighborhood volume anomalies — the rich count-vs-typical items.
    for (const a of anomalies) {
      if (a.datasetId === 'combined') continue
      const fresh = window48.freshness[a.datasetId]
      const freshnessOk = fresh?.eventLagMs != null && fresh.eventLagMs < FRESH_MAX_MS
      const item = anomalyToWireItem(a, { freshnessOk, computedAt: now })
      if (item) wire.push(item)
    }

    // Citywide signals from the indicator engine (already freshness-gated there).
    for (const t of tickerItems) {
      const item = tickerToWireItem(t)
      if (item) wire.push(item)
    }

    // One row per id (anomaly ids are unique per neighborhood×stream; this also
    // guards against an indicator and an anomaly colliding on id).
    const byId = new Map<string, WireItem>()
    for (const w of wire) {
      const existing = byId.get(w.id)
      if (!existing || w.rankScore > existing.rankScore) byId.set(w.id, w)
    }
    return rankWire([...byId.values()])
  }, [anomalies, tickerItems, window48.freshness])

  return { items, isLoading: window48.isLoading || tickerLoading }
}
