// src/cities/oakland/tractRegions.ts
//
// GENERATED — re-run `python3 scripts/build-oakland-tract-regions.py`.
// Census tract (2023) -> Oakland planning region. Centroid-in-polygon,
// weight 1.0, full coverage of the tracts listed (a tract is never split,
// so no ACS mass is lost — structurally immune to SF's partial-crosswalk
// bug). Consumed by aggregateToNeighborhoods(tracts, OAKLAND_TRACT_REGIONS).

import type { TractMapping } from '../../types/census'

export const OAKLAND_TRACT_REGIONS: TractMapping[] = [
  { tractId: '400100', neighborhoods: [{ name: 'NW', weight: 1 }] },
  { tractId: '400200', neighborhoods: [{ name: 'N', weight: 1 }] },
  { tractId: '400300', neighborhoods: [{ name: 'N', weight: 1 }] },
  { tractId: '400400', neighborhoods: [{ name: 'N', weight: 1 }] },
  { tractId: '400500', neighborhoods: [{ name: 'N', weight: 1 }] },
  { tractId: '400600', neighborhoods: [{ name: 'N', weight: 1 }] },
  { tractId: '400700', neighborhoods: [{ name: 'N', weight: 1 }] },
  { tractId: '400800', neighborhoods: [{ name: 'N', weight: 1 }] },
  { tractId: '400900', neighborhoods: [{ name: 'N', weight: 1 }] },
  { tractId: '401000', neighborhoods: [{ name: 'N', weight: 1 }] },
  { tractId: '401100', neighborhoods: [{ name: 'N', weight: 1 }] },
  { tractId: '401200', neighborhoods: [{ name: 'N', weight: 1 }] },
  { tractId: '401300', neighborhoods: [{ name: 'C', weight: 1 }] },
  { tractId: '401400', neighborhoods: [{ name: 'W', weight: 1 }] },
  { tractId: '401500', neighborhoods: [{ name: 'W', weight: 1 }] },
  { tractId: '401600', neighborhoods: [{ name: 'W', weight: 1 }] },
  { tractId: '401800', neighborhoods: [{ name: 'W', weight: 1 }] },
  { tractId: '402200', neighborhoods: [{ name: 'W', weight: 1 }] },
  { tractId: '402400', neighborhoods: [{ name: 'W', weight: 1 }] },
  { tractId: '402500', neighborhoods: [{ name: 'W', weight: 1 }] },
  { tractId: '402600', neighborhoods: [{ name: 'W', weight: 1 }] },
  { tractId: '402700', neighborhoods: [{ name: 'W', weight: 1 }] },
  { tractId: '402801', neighborhoods: [{ name: 'C', weight: 1 }] },
  { tractId: '402802', neighborhoods: [{ name: 'C', weight: 1 }] },
  { tractId: '402900', neighborhoods: [{ name: 'C', weight: 1 }] },
  { tractId: '403000', neighborhoods: [{ name: 'C', weight: 1 }] },
  { tractId: '403100', neighborhoods: [{ name: 'C', weight: 1 }] },
  { tractId: '403301', neighborhoods: [{ name: 'C', weight: 1 }] },
  { tractId: '403302', neighborhoods: [{ name: 'C', weight: 1 }] },
  { tractId: '403402', neighborhoods: [{ name: 'C', weight: 1 }] },
  { tractId: '403501', neighborhoods: [{ name: 'C', weight: 1 }] },
  { tractId: '403502', neighborhoods: [{ name: 'C', weight: 1 }] },
  { tractId: '403600', neighborhoods: [{ name: 'C', weight: 1 }] },
  { tractId: '403701', neighborhoods: [{ name: 'C', weight: 1 }] },
  { tractId: '403702', neighborhoods: [{ name: 'C', weight: 1 }] },
  { tractId: '403800', neighborhoods: [{ name: 'L', weight: 1 }] },
  { tractId: '403900', neighborhoods: [{ name: 'L', weight: 1 }] },
  { tractId: '404000', neighborhoods: [{ name: 'N', weight: 1 }] },
  { tractId: '404101', neighborhoods: [{ name: 'N', weight: 1 }] },
  { tractId: '404102', neighborhoods: [{ name: 'N', weight: 1 }] },
  { tractId: '404300', neighborhoods: [{ name: 'NW', weight: 1 }] },
  { tractId: '404400', neighborhoods: [{ name: 'NW', weight: 1 }] },
  { tractId: '404501', neighborhoods: [{ name: 'NW', weight: 1 }] },
  { tractId: '404502', neighborhoods: [{ name: 'NW', weight: 1 }] },
  { tractId: '404600', neighborhoods: [{ name: 'NW', weight: 1 }] },
  { tractId: '404700', neighborhoods: [{ name: 'NW', weight: 1 }] },
  { tractId: '404800', neighborhoods: [{ name: 'L', weight: 1 }] },
  { tractId: '404900', neighborhoods: [{ name: 'L', weight: 1 }] },
  { tractId: '405000', neighborhoods: [{ name: 'L', weight: 1 }] },
  { tractId: '405100', neighborhoods: [{ name: 'L', weight: 1 }] },
  { tractId: '405200', neighborhoods: [{ name: 'S', weight: 1 }] },
  { tractId: '405301', neighborhoods: [{ name: 'S', weight: 1 }] },
  { tractId: '405302', neighborhoods: [{ name: 'S', weight: 1 }] },
  { tractId: '405401', neighborhoods: [{ name: 'S', weight: 1 }] },
  { tractId: '405402', neighborhoods: [{ name: 'S', weight: 1 }] },
  { tractId: '405500', neighborhoods: [{ name: 'S', weight: 1 }] },
  { tractId: '405600', neighborhoods: [{ name: 'S', weight: 1 }] },
  { tractId: '405700', neighborhoods: [{ name: 'S', weight: 1 }] },
  { tractId: '405800', neighborhoods: [{ name: 'S', weight: 1 }] },
  { tractId: '405901', neighborhoods: [{ name: 'S', weight: 1 }] },
  { tractId: '405902', neighborhoods: [{ name: 'S', weight: 1 }] },
  { tractId: '406000', neighborhoods: [{ name: 'C', weight: 1 }] },
  { tractId: '406100', neighborhoods: [{ name: 'F', weight: 1 }] },
  { tractId: '406201', neighborhoods: [{ name: 'S', weight: 1 }] },
  { tractId: '406202', neighborhoods: [{ name: 'F', weight: 1 }] },
  { tractId: '406300', neighborhoods: [{ name: 'S', weight: 1 }] },
  { tractId: '406400', neighborhoods: [{ name: 'S', weight: 1 }] },
  { tractId: '406500', neighborhoods: [{ name: 'F', weight: 1 }] },
  { tractId: '406601', neighborhoods: [{ name: 'F', weight: 1 }] },
  { tractId: '406602', neighborhoods: [{ name: 'F', weight: 1 }] },
  { tractId: '406700', neighborhoods: [{ name: 'L', weight: 1 }] },
  { tractId: '406800', neighborhoods: [{ name: 'L', weight: 1 }] },
  { tractId: '406900', neighborhoods: [{ name: 'L', weight: 1 }] },
  { tractId: '407000', neighborhoods: [{ name: 'F', weight: 1 }] },
  { tractId: '407101', neighborhoods: [{ name: 'F', weight: 1 }] },
  { tractId: '407102', neighborhoods: [{ name: 'F', weight: 1 }] },
  { tractId: '407200', neighborhoods: [{ name: 'F', weight: 1 }] },
  { tractId: '407300', neighborhoods: [{ name: 'CE', weight: 1 }] },
  { tractId: '407400', neighborhoods: [{ name: 'CE', weight: 1 }] },
  { tractId: '407500', neighborhoods: [{ name: 'CE', weight: 1 }] },
  { tractId: '407600', neighborhoods: [{ name: 'CE', weight: 1 }] },
  { tractId: '407700', neighborhoods: [{ name: 'CE', weight: 1 }] },
  { tractId: '407800', neighborhoods: [{ name: 'CE', weight: 1 }] },
  { tractId: '407900', neighborhoods: [{ name: 'L', weight: 1 }] },
  { tractId: '408000', neighborhoods: [{ name: 'SE', weight: 1 }] },
  { tractId: '408100', neighborhoods: [{ name: 'SE', weight: 1 }] },
  { tractId: '408200', neighborhoods: [{ name: 'CE', weight: 1 }] },
  { tractId: '408300', neighborhoods: [{ name: 'E', weight: 1 }] },
  { tractId: '408400', neighborhoods: [{ name: 'E', weight: 1 }] },
  { tractId: '408500', neighborhoods: [{ name: 'E', weight: 1 }] },
  { tractId: '408600', neighborhoods: [{ name: 'CE', weight: 1 }] },
  { tractId: '408700', neighborhoods: [{ name: 'CE', weight: 1 }] },
  { tractId: '408800', neighborhoods: [{ name: 'CE', weight: 1 }] },
  { tractId: '408900', neighborhoods: [{ name: 'E', weight: 1 }] },
  { tractId: '409100', neighborhoods: [{ name: 'E', weight: 1 }] },
  { tractId: '409200', neighborhoods: [{ name: 'E', weight: 1 }] },
  { tractId: '409300', neighborhoods: [{ name: 'E', weight: 1 }] },
  { tractId: '409400', neighborhoods: [{ name: 'E', weight: 1 }] },
  { tractId: '409500', neighborhoods: [{ name: 'E', weight: 1 }] },
  { tractId: '409600', neighborhoods: [{ name: 'E', weight: 1 }] },
  { tractId: '409700', neighborhoods: [{ name: 'E', weight: 1 }] },
  { tractId: '409800', neighborhoods: [{ name: 'E', weight: 1 }] },
  { tractId: '409900', neighborhoods: [{ name: 'SE', weight: 1 }] },
  { tractId: '410000', neighborhoods: [{ name: 'SE', weight: 1 }] },
  { tractId: '410100', neighborhoods: [{ name: 'E', weight: 1 }] },
  { tractId: '410200', neighborhoods: [{ name: 'E', weight: 1 }] },
  { tractId: '410300', neighborhoods: [{ name: 'E', weight: 1 }] },
  { tractId: '410400', neighborhoods: [{ name: 'E', weight: 1 }] },
  { tractId: '410500', neighborhoods: [{ name: 'W', weight: 1 }] },
  { tractId: '983200', neighborhoods: [{ name: 'C', weight: 1 }] },
]
