/**
 * Mock ticker data for visual testing while the engine worktree
 * provides real Socrata-driven indicators.
 */
import type { TickerItem } from '@/types/ticker'

const now = new Date()

export const MOCK_TICKER_ITEMS: TickerItem[] = [
  {
    id: 'er-response-yoy',
    headline: 'Tenderloin 911 Response: +23% YoY',
    detail: 'Avg 6.2 min vs 5.0 min prior year',
    category: 'anomaly',
    severity: 'negative',
    source: {
      view: '/emergency-response',
      params: { neighborhood: 'Tenderloin' },
      label: 'Emergency Response · Tenderloin',
      datasetId: 'nuek-vuh3',
    },
    sparkData: [42, 45, 48, 51, 56, 62, 58, 64, 68, 72],
    delta: 23.4,
    value: '6.2 min',
    priorValue: '5.0 min',
    freshness: 'daily',
    computedAt: now,
    priority: 90,
  },
  {
    id: 'biz-net-formation',
    headline: 'Business Openings +12% vs Prior Year',
    detail: '847 opened, 412 closed — net +435',
    category: 'trend',
    severity: 'positive',
    source: {
      view: '/business-activity',
      label: 'Business Activity · Citywide',
      datasetId: 'g8m3-pdis',
    },
    sparkData: [310, 345, 380, 420, 395, 440, 470, 510, 490, 530],
    delta: 12.0,
    value: '+435 net',
    freshness: 'daily',
    computedAt: now,
    priority: 70,
  },
  {
    id: 'compliance-240210',
    headline: 'Res. 240210: 10.3% vs 50% Target',
    detail: 'Ethnic media ad spend — $178K shortfall',
    category: 'compliance',
    severity: 'alert',
    source: {
      view: '/city-budget',
      params: { tab: 'advertising' },
      label: 'Budget · Advertising Compliance',
    },
    sparkData: [8, 9, 10, 11, 10, 9, 10, 11, 10, 10],
    delta: -79.4,
    value: '10.3%',
    freshness: 'monthly',
    computedAt: now,
    priority: 85,
  },
  {
    id: 'parking-revenue',
    headline: 'Parking Revenue -8.2% vs Last Year',
    detail: '$4.1M this month vs $4.5M prior',
    category: 'trend',
    severity: 'negative',
    source: {
      view: '/parking-revenue',
      label: 'Parking Revenue · Citywide',
      datasetId: 'imvp-dq3v',
    },
    sparkData: [450, 420, 430, 415, 400, 410, 395, 385, 390, 380],
    delta: -8.2,
    value: '$4.1M',
    priorValue: '$4.5M',
    freshness: 'daily',
    computedAt: now,
    priority: 70,
  },
  {
    id: 'crime-violent',
    headline: 'Violent Crime -6.1% Citywide',
    detail: '342 incidents vs 364 prior year',
    category: 'trend',
    severity: 'positive',
    source: {
      view: '/crime-incidents',
      params: { categories: 'violent' },
      label: 'Crime Incidents · Violent',
      datasetId: 'wg3w-h783',
    },
    sparkData: [38, 35, 37, 34, 36, 33, 35, 32, 34, 31],
    delta: -6.1,
    value: '342',
    priorValue: '364',
    freshness: 'daily',
    computedAt: now,
    priority: 72,
  },
  {
    id: '311-anomaly',
    headline: 'Mission 311 Volume 2.8σ Above Baseline',
    detail: 'Graffiti + street cleaning driving spike',
    category: 'anomaly',
    severity: 'negative',
    source: {
      view: '/311-cases',
      params: { neighborhood: 'Mission', map_mode: 'anomaly' },
      label: '311 Cases · Mission District',
      datasetId: 'vw6y-z8j6',
    },
    sparkData: [120, 115, 130, 125, 140, 155, 180, 210, 195, 220],
    delta: 42.5,
    value: '2.8σ',
    freshness: 'daily',
    computedAt: now,
    priority: 88,
  },
  {
    id: 'traffic-fatalities',
    headline: 'Traffic Fatalities: 3 This Month',
    detail: 'DUI crashes up 15% — 2 pedestrian involved',
    category: 'trend',
    severity: 'negative',
    source: {
      view: '/traffic-safety',
      label: 'Traffic Safety · Citywide',
      datasetId: 'ubvf-ztfx',
    },
    sparkData: [2, 1, 3, 2, 4, 1, 2, 3, 1, 3],
    delta: 15.0,
    value: '3',
    freshness: 'daily',
    computedAt: now,
    priority: 75,
  },
  {
    id: 'citations-oos',
    headline: '12,400 Citations · 18% Out-of-State',
    detail: 'Double-parking and meter violations leading',
    category: 'milestone',
    severity: 'neutral',
    source: {
      view: '/parking-citations',
      label: 'Parking Citations · Citywide',
      datasetId: 'ab4h-6ztd',
    },
    sparkData: [1100, 1050, 1150, 1200, 1180, 1250, 1300, 1280, 1350, 1400],
    delta: 4.2,
    value: '12.4K',
    freshness: 'daily',
    computedAt: now,
    priority: 60,
  },
  {
    id: 'campaign-cycle',
    headline: 'Campaign Cycle: $8.4M Raised',
    detail: '127 committees — Mayor race dominates',
    category: 'milestone',
    severity: 'neutral',
    source: {
      view: '/campaign-finance',
      label: 'Campaign Finance · Current Cycle',
      datasetId: 'pitq-e56w',
    },
    sparkData: [200, 350, 500, 800, 1200, 1800, 2400, 3100, 3800, 4200],
    delta: 34.0,
    value: '$8.4M',
    freshness: 'weekly',
    computedAt: now,
    priority: 65,
  },
  {
    id: 'demographics-income',
    headline: 'Income Varies 4.2x Across SF Neighborhoods',
    detail: '$42K median (Tenderloin) to $177K (Sea Cliff)',
    category: 'milestone',
    severity: 'neutral',
    source: {
      view: '/demographics',
      params: { variable: 'median_income' },
      label: 'Demographics · Income',
    },
    sparkData: [42, 58, 72, 85, 95, 110, 125, 140, 158, 177],
    freshness: 'monthly',
    computedAt: now,
    priority: 55,
  },
]
